More resilient image creation

diff --git a/misc/docker_tests/base_images/centos_6/Dockerfile b/misc/docker_tests/base_images/centos_6/Dockerfile
--- a/misc/docker_tests/base_images/centos_6/Dockerfile
+++ b/misc/docker_tests/base_images/centos_6/Dockerfile
@@ -3,5 +3,7 @@ FROM centos:centos6
 MAINTAINER Lion Krischer
 
 RUN rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
+# Can fail on occasion.
+RUN yum -y upgrade || true
 RUN yum install -y numpy scipy gcc-gfortran python-matplotlib python-sqlalchemy0.8 python-lxml python-mock python-basemap python-basemap-data
 RUN easy_install flake8 suds-jurko future
diff --git a/misc/docker_tests/base_images/debian_6_squeeze/Dockerfile b/misc/docker_tests/base_images/debian_6_squeeze/Dockerfile
--- a/misc/docker_tests/base_images/debian_6_squeeze/Dockerfile
+++ b/misc/docker_tests/base_images/debian_6_squeeze/Dockerfile
@@ -2,6 +2,9 @@ FROM debian:squeeze
 
 MAINTAINER Lion Krischer
 
-RUN apt-get update
-RUN apt-get -y install python-numpy python-scipy gfortran python-matplotlib python-sqlalchemy python-lxml python-mock python-mpltoolkits.basemap python-mpltoolkits.basemap-data python-pip
+# Can fail on occasion.
+RUN apt-get update && apt-get upgrade || true
+RUN apt-get -y install python-numpy python-scipy gfortran python-matplotlib python-sqlalchemy python-lxml python-mock python-pip libgeos-3.2.0 python-dev libgeos-dev
 RUN pip install flake8 suds-jurko future
+# Squeeze unfortunately has no basemap packages.
+RUN GEOS_DIR=/usr/lib pip install basemap
diff --git a/misc/docker_tests/base_images/debian_7_wheezy/Dockerfile b/misc/docker_tests/base_images/debian_7_wheezy/Dockerfile
--- a/misc/docker_tests/base_images/debian_7_wheezy/Dockerfile
+++ b/misc/docker_tests/base_images/debian_7_wheezy/Dockerfile
@@ -2,6 +2,7 @@ FROM debian:wheezy
 
 MAINTAINER Lion Krischer
 
-RUN apt-get update
+# Can fail on occasion.
+RUN apt-get update && apt-get upgrade || true
 RUN apt-get -y install python-numpy python-scipy gfortran python-matplotlib python-sqlalchemy python-lxml python-mock python-mpltoolkits.basemap python-mpltoolkits.basemap-data python-pip
 RUN pip install flake8 suds-jurko future
